# Generated by Django 2.2.5 on 2019-09-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('time', 'FULL DAY'), ('timesince', 'FIRST HALF'), ('timeuntil', 'SECOND HALF')], max_length=100),
        ),
    ]
