# Generated by Django 2.2.5 on 2019-09-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0002_auto_20190923_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='college',
            field=models.CharField(choices=[('vesa', 'VES College of Architecture'), ('vesit', 'VES Institute of Technology'), ('vesp', 'VES College of Pharmacy'), ('vesl', 'VES College of Law'), ('vesim', 'VES Institute of Management')], max_length=100),
        ),
    ]
