# Generated by Django 2.2.5 on 2019-09-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0004_auto_20190924_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('Full Day', 'FULL DAY'), ('First Half', 'FIRST HALF'), ('Second Half', 'SECOND HALF')], max_length=100),
        ),
    ]
