# Generated by Django 2.2.5 on 2019-09-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0007_booking_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='approve',
            field=models.CharField(choices=[('Not Approved', 'Not Approved'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Not Approved', max_length=100),
        ),
    ]
