# Generated by Django 2.2.5 on 2019-09-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksite', '0008_auto_20190924_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='approve',
            field=models.CharField(choices=[('Not Approved', 'Not Approved'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
